### ISSUE TITLE
split_file_to_collection issue

### ISSUE THREAD

**Issue by lecorguille** [bgruening/galaxytools#1009]
Our instance was stuck with this log
```
[split_file_003590.txt] for output [list_output_txt] (1845.765 ms)
galaxy.model.store.discover DEBUG 2020-06-23 15:59:11,524 (57485) Created dynamic collection dataset for path [/shared/mfs/data/galaxy/jobs/057/57485/working/out/split_file_003310.txt] with element identifier [split_file_003310.txt] for output [list_output_txt] (1280.837 ms)
galaxy.model.store.discover DEBUG 2020-06-23 15:59:11,583 (57483) Created dynamic collection dataset for path [/shared/mfs/data/galaxy/jobs/057/57483/working/out/split_file_003302.txt] with element identifier [split_file_003302.txt] for output [list_output_txt] (1449.770 ms)
```
We had to restart the server
And eventually, got this:
```
galaxy.tool_util.output_checker DEBUG 2020-06-23 15:14:11,869 job failed, detected state generic_error, standard error is - [Traceback (most recent call last):
  File "/shared/mfs/data/galaxy/mutable-data/shed_tools/toolshed.g2.bx.psu.edu/repos/bgruening/split_file_to_collection/e77b954f0da5/split_file_to_collection/split_file_to_collection.py", line 293, in <module>
    main()
  File "/shared/mfs/data/galaxy/mutable-data/shed_tools/toolshed.g2.bx.psu.edu/repos/bgruening/split_file_to_collection/e77b954f0da5/split_file_to_collection/split_file_to_collection.py", line 52, in main
    split_by_record(args, in_file, out_dir, top, ftype)
  File "/shared/mfs/data/galaxy/mutable-data/shed_tools/toolshed.g2.bx.psu.edu/repos/bgruening/split_file_to_collection/e77b954f0da5/split_file_to_collection/split_file_to_collection.py", line 170, in split_by_record
    for count in range(0, numnew)
  File "/shared/mfs/data/galaxy/mutable-data/shed_tools/toolshed.g2.bx.psu.edu/repos/bgruening/split_file_to_collection/e77b954f0da5/split_file_to_collection/split_file_to_collection.py", line 170, in <listcomp>
    for count in range(0, numnew)
OSError: [Errno 24] Too many open files: './out/split_file_051196.txt'
```
I tried to list the containt of the working directory
```
$ ll /shared/mfs/data/galaxy/jobs/057/57476/working/out/*
-bash: /bin/ls: Argument list too long
```

According to @mvdbeek 
> That’s a bug in split_file_to_collection.py. https://github.com/bgruening/galaxytools/blob/master/tools/text_processing/split_file_to_collection/split_file_to_collection.py#L168 never closes the file

**Comment by bernt-matthias** [comment]
Maybe like so: https://github.com/bgruening/galaxytools/pull/1012

**Comment by bernt-matthias** [comment]
@lecorguille can you test the new tool version? then we can close this issue.

**Comment by lecorguille** [comment]
Let's close this issue.
I will reopen if needed. Thanks a bunch!
