### ISSUE TITLE
Readd testing with condor

### ISSUE THREAD

**Issue by simonbray** [bgruening/galaxytools#1057]
Testing was previously done with a condor job runner, but this started causing all tests to fail with the following error:
```
 Traceback (most recent call last):
  File "/tmp/tmpay_nkwl3/galaxy-dev/lib/galaxy/jobs/runners/__init__.py", line 137, in run_next
    method(arg)
  File "/tmp/tmpay_nkwl3/galaxy-dev/lib/galaxy/jobs/runners/condor.py", line 160, in queue_job
    external_job_id, message = condor_submit(submit_file)
  File "/tmp/tmpay_nkwl3/galaxy-dev/lib/galaxy/jobs/runners/util/condor/__init__.py", line 77, in condor_submit
    message = commands.execute(('condor_submit', submit_file))
  File "/tmp/tmpay_nkwl3/galaxy-dev/lib/galaxy/util/commands.py", line 95, in execute
    return _wait(cmds, input=input, shell=False, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/tmp/tmpay_nkwl3/galaxy-dev/lib/galaxy/util/commands.py", line 112, in _wait
    p = subprocess.Popen(cmds, **popen_kwds)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'condor_submit': 'condor_submit'
```
which indicates some error with htcondor installation.

I couldn't work out the cause of the error, so I removed the condor job config file from the planemo test command for now in this commit: https://github.com/bgruening/galaxytools/pull/1056/commits/c678f9b706df0b235ba1415132d96dc405b3374e

However, it would be good if this could be fixed at some point.

**Comment by bernt-matthias** [comment]
Seems outdated, or is there still any use in using condor in testing?

**Comment by bgruening** [comment]
Its the better testing imho, we had some tools that crashed with the local runner - imageJ. Not sure if this is still the case.

But we can close and come back if we see this again.
