### ISSUE TITLE
opt_validate error on command line

### ISSUE THREAD

**Issue by vin6** [bgruening/galaxytools#62]
Got this error trying to implement MACS2 callpeak...this doesn't happen with MACS1.4:

Traceback (most recent call last):
  File "/local/cluster/bin/macs2", line 362, in <module>
    main()
  File "/local/cluster/bin/macs2", line 45, in main
    run( args )
  File "/local/cluster/lib/python2.7/site-packages/MACS2/callpeak.py", line 55, in run
    options = opt_validate( args )
  File "/local/cluster/lib/python2.7/site-packages/MACS2/OptValidator.py", line 184, in opt_validate
    if options.refine_peaks:
AttributeError: 'Namespace' object has no attribute 'refine_peaks'
        Full Command:                      macs2 callpeak -t aGFP_align_sorted.bam -c input_align_sorted.bam -f BAM -g 245000000 -p 1.00e-5 -n aGFP --verbose 3

**Comment by bgruening** [comment]
@vin6 is this still a problem? We have improved the wrappers quite a lot.
I will close this, but please feel free to reopen if there is still a problem.
