### ISSUE TITLE
SortMeRNA data manager - Broken URL ?

### ISSUE THREAD

**Issue by arbernard** [bgruening/galaxytools#683]
Hello everyone,

As requested by @bebatut, I'm creating this issue to warn you about a problem I encountered this morning with the current revision of the SortMeRNA data manager available on the MTS (revision 7d2252852f96).

When I try to execute the data manager it fails and it displays the following errors:

```
Fatal error: Exit code 1 (Error)
Traceback (most recent call last):
  File "/projet/galaxyprod/galaxyclermont/shed_tools/toolshed.g2.bx.psu.edu/repos/rnateam/data_manager_sortmerna_database_downloader/7d2252852f96/data_manager_sortmerna_database_downloader/data_manager/data_manager_sortmerna_download.py", line 213, in 
    target_dir)
  File "/projet/galaxyprod/galaxyclermont/shed_tools/toolshed.g2.bx.psu.edu/repos/rnateam/data_manager_sortmerna_database_downloader/7d2252852f96/data_manager_sortmerna_database_downloader/data_manager/data_manager_sortmerna_download.py", line 171, in download_db
    filepath = download_archive(version)
  File "/projet/galaxyprod/galaxyclermont/shed_tools/toolshed.g2.bx.psu.edu/repos/rnateam/data_manager_sortmerna_database_downloader/7d2252852f96/data_manager_sortmerna_database_downloader/data_manager/data_manager_sortmerna_download.py", line 88, in download_archive
    r = requests.get(url, stream=True)
  File "/projet/galaxyprod/galaxyclermont/galaxy/.venv/lib/python2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/projet/galaxyprod/galaxyclermont/galaxy/.venv/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/projet/galaxyprod/galaxyclermont/galaxy/.venv/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/projet/galaxyprod/galaxyclermont/galaxy/.venv/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/projet/galaxyprod/galaxyclermont/galaxy/.venv/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /biocore/sortmerna/archive/2.1b.tar.gz (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known',))

```
It seems that it tries to access a file that no longer exists on the /biocore/sortmerna/ Github repository.

Thanks in advance for the fix :)

PS: would it be possible to allow the user to select which databanks must be downloaded instead of downloading all of them in one go ?

**Comment by bgruening** [comment]
@arbernard can you dig our this file out of the github history? Then a fix would be easy.

**Comment by arbernard** [comment]
It seems that the databanks are included in a rRNA_databases folder of the source code archive.

The URL is https://github.com/biocore/sortmerna/archive/2.1b.tar.gz (and the link is not broken). 

I bet that this is already the URL used in the data manager so I don't get why I get an error when I execute the data manager...

**Comment by bgruening** [comment]
@arbernard can you try it in a Docker image and see if this works?

**Comment by arbernard** [comment]
I'm not familiar with docker, how do i do that ?

In the meantime, I've just tried to install and execute the data_manager on another galaxy instance (different network and environment) and it worked without issue. I bet there is something preventing the proper download of the archive on the other instance I was using before.

**Comment by bgruening** [comment]
OK. This is what I wanted to check, it this was a network issue. Sorry to hear that :(
I will close this issue then. Let us know if we can help.

**Comment by arbernard** [comment]
I've reported the issue to the platform. Sorry for the false alarm here ^^
